name: gym_detector_ios
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.2
  flutter_timer_countdown: ^1.0.5 # 倒计时器 
  image_picker: ^1.1.2 # 单图片照片采取器
  dotted_border: ^2.0.0
  video_thumbnail: ^0.5.1 # 视频压缩图
  shared_preferences: ^2.3.2 # 暂存用户偏好数据
  fl_chart:   #绘制曲线图
  http:  # http请求
  provider: ^6.0.5 #监听器
  cloudinary_public: ^0.23.1 #图片云床
  flutter_screenutil: ^5.6.1 # 屏幕自适应
  multi_image_picker_view: ^1.1.0 #多图片采取器
  video_player: ^2.9.2 #视频时长获取
  crypto: ^3.0.6  #哈希加密密码
  bcrypt: ^1.1.3
  cached_network_image: ^3.4.1  #图片缓存
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  audioplayers_darwin: 6.0.0
  file_picker: ^8.0.0
  audioplayers: ^6.0.0
  photo_view: ^0.14.0
  phone_state: ^1.0.3
  image_gallery_saver: ^2.0.3
  scroll_to_index: ^3.0.1
  open_filex: ^4.3.2
  visibility_detector: ^0.4.0+2
  super_tooltip: ^1.0.1
  pull_to_refresh: ^2.0.0
  azlistview_plus: ^3.0.0
  lpinyin: ^2.0.3

  netease_common_ui:
    ">=9.7.3 <10.0.0"
  netease_corekit_im:
    ">=9.7.3 <10.0.0"
  netease_corekit:
    ">=1.2.1 <1.3.0"
  netease_common: ^1.0.4
  
  nim_core: ^1.7.4
  nim_contactkit: 
    ">=9.7.3 <10.0.0"
  nim_conversationkit:
    ">=9.7.3 <10.0.0"
  nim_chatkit:
    ">=9.7.3 <10.0.0"
  nim_teamkit:
    ">=9.7.3 <10.0.0"
  nim_searchkit:
    ">=9.7.3 <10.0.0"
  path_provider: ^2.1.5
   


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo/logo.png"

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/gymplan_images/
    - assets/user_images/
    - assets/dynamic_images/
    - assets/bar_images/
    - assets/bodydata_images/
    - assets/logo/
    - assets/ui_plugins_images/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf