# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # 添加 post_install 块来设置部署目标和额外的构建设置
  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0' # 或者你希望设置的其他版本
        end
      end
    end

    # 引入 Flutter 额外的 iOS 构建设置
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
    end
  end

  # 定义额外的构建设置方法
  def flutter_additional_ios_build_settings(target)
    # 你可以在这里添加额外的构建设置，例如：
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end